# Generated by Django 2.2.6 on 2019-10-15 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('thumbUp', models.IntegerField(default=0)),
                ('thumbDown', models.IntegerField(default=0)),
            ],
        ),
    ]
